### ISSUE TITLE
select-insert when binding strings

### ISSUE THREAD

**Issue by krisbaehr** [IBM/nodejs-idb-connector#114] opened 2020-03-25 17:07 UTC
**Describe the bug**
When performing a select-insert, and adding multiple rows, the string data types are written as blanks. Also, since timestamps are bound as strings, an insert with a timestamp results in an error since '' is not a valid timestamp. Inserting just one row with this method works as expected.

**To Reproduce**
1. Create a simple table with a string and a decimal value
2. Run the script below

**Expected behavior**
When inserting multiple rows, the string column in the table should contain the value that was bound, instead of blank.

**Screenshots**
Inserting one row (works):
![image](https://user-images.githubusercontent.com/33702300/77564410-aae98c80-6e90-11ea-9dae-b4d2225966b6.png)

![image](https://user-images.githubusercontent.com/33702300/77564046-1f6ffb80-6e90-11ea-9531-7ff0fcac995d.png)

Inserting two rows (does not work):
![image](https://user-images.githubusercontent.com/33702300/77564333-8e4d5480-6e90-11ea-9edc-e856dff0152d.png)

![image](https://user-images.githubusercontent.com/33702300/77564123-3878ac80-6e90-11ea-8d53-7a3f181b2e23.png)

[server4.txt](https://github.com/IBM/nodejs-idb-connector/files/4382334/server4.txt)

Node.js version: v10.16.3
idb-connector version: 1.2.7
IBM i version: 3 7

** Debug Output **
Prepare().                                                                                        
SQLPrepare(0): select * from final table ( insert into crpcnad (uid, adid) values (?, ?), (?, ?) )
BindParamAsync().                                                                                 
SQLBindParameter(0) TYPE[ 1] SIZE[ 10] DIGI[0] IO[1] IND[ -3] INDEX[0]                            
SQLBindParameter(0) TYPE[ 3] SIZE[  8] DIGI[7] IO[1] IND[  8] INDEX[1]                            
SQLBindParameter(0) TYPE[ 1] SIZE[ 10] DIGI[0] IO[1] IND[ -3] INDEX[2]                            
SQLBindParameter(0) TYPE[ 3] SIZE[  8] DIGI[7] IO[1] IND[  8] INDEX[3]                            
Execute().                                                                 
SQLExecuteAsync(0):                                                        
SQLNUMRESULTSCOLS(0) Column Count = 3                                      
DescCol(0)      index[0]        Type[DECIMAL]   Scale[0]        Precise[9] 
DescCol(0)      index[1]        Type[CHAR]      Scale[0]        Precise[10]
DescCol(0)      index[2]        Type[DECIMAL]   Scale[0]        Precise[9] 
SQLFreeStmt: stmth 3 [SQL_DROP]                                            
SQLFreeStmt(0)                                                             
SQLDisconnect: conn obj [18034c550] handler [2]                            
SQLFreeConnect: conn obj [18034c550] handler [2]                           
SQLFreeConnect[0]

**Comment by dmabupt** [comment] 2020-03-28 01:56
Hello @krisbaehr , My test results are sort of different. The two records are inserted but the CHAR fields are empty --

`[{"CONTACTID":"          ","ADDRESSID":"1"},{"CONTACTID":"          ","ADDRESSID":"2"}]`.

My table was created by `CREATE OR REPLACE TABLE xumeng.testp(ContactId CHAR(10), AddressId DECIMAL)`. Any my environment is idb v1.2.7 + Node.js v12.16.1.

BTW, the API bindparam() is deprecated in v1.2.7. Would you use the new API bindParameters() and 1-D array?
```
let params = [ 'foo', 1, 'bar', 2, ];

statement.prepare(sql, (error) => {
	statement.bindParameters(params, (error) => {
		statement.execute((error) => {  
```
In my test, the new API produced the expected results although some execute error happened (may need investigation) --
```
Execute error...
[ 'foo', 1, 'bar', 2 ]

undefined:0

[ 'foo', 1, 'bar', 2 ]
```
My test code -- [testp.txt](https://github.com/IBM/nodejs-idb-connector/files/4396505/testp.txt)

**Comment by dmabupt** [comment] 2020-03-28 02:46
Hello @krisbaehr , The root cause is that idb-connector code check the column count -- https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L1027

- If the there is NO column, then idb-connector assumes there is NO result-set. So it does not need to **bind** columns and **fetch** the data. (like INSERT, UPDATE, etc) The binding parameters will be handled seperately and correctly.

- If there are 1 or more columns, idb-connector assumes there is a result-set. And then it **bind** columns and **fetch** the data. (like SELECT)

In this case, this SELECT-like statement confuses idb-connector since it has two columns. So idb-connector follows the result-set process, bind the columns, but fetch nothing. I guess that the second binding operation destroy the CHAR field binding.

So we may need to find out a better solution to determine if there is a result-set available.

**Comment by dmabupt** [comment] 2020-03-29 02:10
Hello @krisbaehr , Would you try to change this line `const STRING = 1;` to `const STRING = 0;`?

**Comment by dmabupt** [comment] 2020-03-29 02:39
BTW, the parameter of API execute() should be the output binding parameters -- `statement.execute((out, error) => {...`

And the API `bindParam()` will be deprecated since v1.2.7. It is recommended to use the new and simplified API `bindParameters()` like this -->
```
// let params = [
// 	['foo', idb.SQL_PARAM_INPUT, STRING],
// 	[1, idb.SQL_PARAM_INPUT, DECIMAL],
// 	['bar', idb.SQL_PARAM_INPUT, STRING],
// 	[2, idb.SQL_PARAM_INPUT, DECIMAL]
// ];

let params = [ 'foo', 1, 'bar', 2];

statement.prepare(sql, (error) => {
	statement.bindParameters(params, (error) => {
		statement.execute((out, error) => {  
...
```

**Comment by krisbaehr** [comment] 2020-03-30 15:05
@dmabupt Thank you for the tips! I changed the script to set the STRING constant to 0 and everything worked. I tried inserting one row and multiple rows and it worked for both.

I also tried the new bindParameters() syntax as suggested. The two rows were inserted but suffered from the same issue where the string column was inserted as blank. Inserting one row worked.

**Comment by dmabupt** [comment] 2020-03-30 15:15
> @dmabupt Thank you for the tips! I changed the script to set the STRING constant to 0 and everything worked. I tried inserting one row and multiple rows and it worked for both.
> 
> I also tried the new bindParameters() syntax as suggested. The two rows were inserted but suffered from the same issue where the string column was inserted as blank. Inserting one row worked.

Ah... Yes, 

I changed the bindParameters() code to use STRING(0) by default on my test system. But I have not updated the code in this repo yet. I will add the patch in the next version.

Thanks for the reminder!

**Comment by dmabupt** [comment] 2020-04-01 15:14
Commit 48d4963 fixed the bindParameters() issue. Close this issue for now.

**Closed by dmabupt** 2020-04-01 15:14 UTC
Labels: bug
